# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7157a7686469683f55755be7cd496e504813fe5adfe8df7686357110a953d6308c90de13bf95470b05adf395f76901666c13ec338ce5e3e369217244b9e20b

test:
  secret_key_base: 9315ae7dc0b67889582159208da6706d7701550c520b50e56b37ae29476aa5abd01f0a0c2188e9c52b2e3e45f615ea3c18b939cadd5c7bf29a0d256f7e2ac755

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
